version: "3"

services:
  swag:
    image: linuxserver/swag
    container_name: swag
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bishkek
      - URL=achakey.online # Ваш домен
      - SUBDOMAINS=www, # Указать поддомены, если необходимо
      - VALIDATION=http
      - EMAIL=motionwebteam@gmail.com # Ваш email для Let's Encrypt
      - DNSPLUGIN= # Установить, если требуется использовать плагин DNS
      - STAGING=false # Установить true для использования Let's Encrypt staging сервера (для тестирования)
    volumes:
      - ./config:/config
      - ./nginx.conf:/config/nginx/site-confs/default # Путь к вашему файлу nginx.conf
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - REACT_APP_API_URL=https://api.achakey.online # URL вашего бэкенда Python
    networks:
      - frontend-network

networks:
  frontend-network:
