export { default as Header } from "../components/header/Header";
export { default as Basket } from "./basket/Basket";
export { default as AllPlaylist } from "../components/playlist/AllPlaylist";
export { default as Home } from "../components/Home/index";
// export { default as Main } from "./main/Main";
export { default as MyPlaylist } from "./myPlaylist/MyPlaylist";
export { default as ResetPasswordEmailPage } from "./resetPassword/ResetPassword";
export { default as ResetPasswordPhonePage } from "./resetPassword/ResetPasswordPhonePage";
export { default as AccountManagamentPage } from "./accountManagement/AccountManagamentPage";
export { default as ChangePasswordPage } from "./accountManagement/ChangePasswordPage";
export { default as EmailVerifyPage } from "./emailVerify/EmailVerify";
