export { default as Header } from "../components/header/Header";
export { default as Basket } from "./basket/Basket";
export { default as AllPlaylist } from "../components/playlist/AllPlaylist";
export { default as Home } from "../components/Home/index";
// export { default as Main } from "./main/Main";
export { default as MyPlaylist } from "./myPlaylist/MyPlaylist";
export { default as ResetPasswordEmailPage } from "./resetPassword/ResetPassword";
export { default as ResetPasswordPhonePage } from "./resetPassword/ResetPasswordPhonePage";
export { default as AccountManagamentPage } from "./accountManagement/AccountManagamentPage";
export { default as ChangePasswordPage } from "./accountManagement/ChangePasswordPage";
export { default as Navigation } from "../global-audio-player-excerpt/AudioPlayerExcerpt";
export { default as AudioPlayerBottom } from "../global-audio-player/audioPlayerBottom";
export { default as NotFound } from "../components/404/NotFound";
export { default as DetailsAlbums } from "../pages/details-albums/DetailsAlbums";
export { default as ExcerptPlayList } from "../pages/excerpt-playlist/ExcerptPlayList";
export { default as PrivacyPolicy } from "../components/footer/PrivacyPolicy";
export { default as PublicOffer } from "../components/footer/PublicOffer";
